language: elixir
dist: xenial
elixir: 1.9.1
otp_release: 22.0
branches:
  only:
    - master
install:
  - mix local.hex --force
  - mix local.rebar --force
before_script: make travis-init
script: make travis
deploy:
  - provider: script
    skip_cleanup: true
    script: make travis-deploy
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: Tt1+JE+0SoW976670Q52ur30syqzXRxdxMAtLh30sFo1E6eHih0LYZlWEO8nUW3CCFTTD77hDfH+2M/iSHBqtHq2hNfuXsvrbhoXO/KRwuHkC0EMsQaQCrbQ9l5csAZ7AB/p5hqdeasy8lBUE/JsdJzuKDC23MGjA7k9owtD0t31BqOUVlKC8UdBR3f0zn8LAzkTw2H4jCUfOEmqjoGwggs10CSGGVATyo+so0q0/8up6JDM/adrSKwg7QUMGHhZQdK2DbN3BSpE3ycBaKLbwUkuzRj0WqRGqWGDy3cdS2W809RCcmDlax00UoZr4kLS4qhQdTwgcAss+o4nnPo5qEpIUaVcYwtl0ymFMezl5L3erUR0V03R0+pKJBgeQhaj5v1TzzLptgpE4C0x1UpbfVARxYxtzCNJQjbMYxoAs2uuGTJLfMiEFeccmkK9SYTKbd95Xy3uzYBEt3gEKTUli8KrGPmE8v+kYawsdzBxSfzuMHdQbqmYPsb5UV1Bnpp08GTV/mtJqKgToxtT/JkMmOJ5eLVKh8WRA2fFOd9vglm0bv1fx09LSNGn4xfANYcM3xnQew/PTWBW0KyvH4vyR/aVYAqVW4VzHl64nruz0+yl1WwnoUx3kawVMNIs7J+9POkiwN66TOQMSJqtKXLXq/6NOMpi5iHgW5e0WFoSN1E=
    on:
      repo: ArcBlock/grpc-builder
      branch: master
env:
  matrix:
    - MIX_ENV=test
